#!/bin/bash -e
which realpath &>/dev/null || realpath() {
	mkdir -p "$1"
	echo $(cd "$1" && pwd)
}

recipe=$1
path=$(realpath "$2")
bootstrap=$(readlink "$0" || echo "$0")
lib=$(realpath $(dirname "$bootstrap"))

mkdir -p "$path"
case $recipe in
	rails)
		if [ $(ruby -e 'print RUBY_VERSION') != '2.1.1' ]
		then
			echo "Ruby 2.1.1 is required, but we found: $(ruby -v)"
			exit 1
		fi

		cat <<-RUBY > "$path/Gemfile"
			source 'https://rubygems.org'
			ruby '2.1.1'
			gem 'rails', '~> 4.1'
			RUBY
		cd "$path"
		bundle update
		bundle exec rails new . \
			--template="$lib/rails/template.rb" \
			--database=postgresql \
			--skip-test-unit \
			--skip-gemfile \
			--skip-bundle
		;;
	*)
		;;
esac

git init
git add .
git commit -am 'Initial commit'
