#!/bin/bash -e
if [ -z "$2" ]
then
	echo 'Please specify a project directory.'
	exit 1
fi

# Normalize GNU and OSX/BSD utils
which realpath &>/dev/null || realpath() {
	mkdir -p "$1"
	echo $(cd "$1" && pwd)
}
sed() {
	perl -pi -e "$@"
}

recipe="$1"
path="$(realpath "$2")"
bootstrap="$(readlink "$0" || echo "$0")"
lib="$(realpath $(dirname "$bootstrap"))"
app_name="$(basename $path)"

mkdir -p "$path"
case "$recipe" in
	rails)
		cat <<-RUBY > "$path/Gemfile"
			source 'https://rubygems.org'
			ruby '2.2.0'
			gem 'rails', '~> 4.2.0'
			RUBY
		cd "$path"
		gem install bundler
		bundle update
		bundle exec rails new . \
			--template="$lib/rails/template.rb" \
			--database=postgresql \
			--skip-test-unit \
			--skip-turbolinks \
			--skip-gemfile \
			--skip-bundle
		;;
	node)
		cd "$path"
		cp -r "$lib/node/." .
		sed "s/APP_NAME/$app_name/g" 'app/index.html' 'README.md'
		npm install
		;;
	npm)
		cd "$path"
		cp -r "$lib/npm/." .
		sed "s/APP_NAME/$app_name/g" 'README.md' 'package.json' 'spec/index_spec.js'
		npm install
		"$(npm bin)/jasmine" init
		;;
	aur)
		cd "$path"
		cp -r "$lib/aur/." .
		sed "s/APP_NAME/$app_name/g" 'README.md' 'bin/app_name' 'doc/app_name.md'
		mv 'bin/app_name' "bin/$app_name"
		mv 'doc/app_name.md' "doc/$app_name.md"
		;;
	*)
		echo 'Please specify a valid recipe.'
		exit 1
		;;
esac

git init
git add .
git commit -am 'Initial commit'
