default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  <%
    # Use template0 if template1 is not set to UTF8 encoding.
    'template: template0' unless PG.connect(dbname: 'postgres')
      .exec(%q{select * from pg_database where datname = 'template1' and datcollate like '%UTF8%'})
      .any?
  %>

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test
