source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '~> 4.1.8'
gem 'puma'
gem 'pg'

gem 'uglifier'
gem 'handlebars_assets'
gem 'jquery-rails'
gem 'lodash-rails'

gem 'sass-rails'

group :development do
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'wdm' if Gem.win_platform?
  gem 'spring-commands-rspec'

  gem 'heroku_san'
  gem 'travis'
end

group :development, :test do
  gem 'pry-rails'

  gem 'rspec-rails'

  gem 'jasmine-rails'
  gem 'sinon-rails'
  gem 'jasmine-jquery-rails'
end

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'database_cleaner'
end
