source 'https://rubygems.org'

ruby '2.1.1'

gem 'foreman'

gem 'rails', '~> 4.0'
gem 'pg'
gem 'puma'

gem 'uglifier'
gem 'handlebars_assets'
gem 'jquery-rails'
gem 'lodash-rails'
gem 'sass-rails'

group :development do
  gem 'zeus'
  gem 'heroku_san'
  gem 'travis'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'jasmine-rails'
  gem 'sinon-rails'
  gem 'jasmine-jquery-rails'
end

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner'
end
